name: enjoei_product_flutter_speedcode
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/products/tanktop/
    - assets/images/profiles/

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-300.woff
          weight: 300
        - asset: assets/fonts/ProximaNova-400.woff
          weight: 400
        - asset: assets/fonts/ProximaNova-600.woff
          weight: 600
        - asset: assets/fonts/ProximaNova-700.woff
          weight: 700
        - asset: assets/fonts/ProximaNova-800.woff
          weight: 800
